name: bambino_env
channels:
  - pytorch
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python=3.11 # or don't specify the version and use the latest stable Python
  - mamba
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=1.6.1  
  - pytorch::pytorch-cuda=12.1
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision


# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64